CREATE DATABASE HGAMES; 
USE HGAMES; 

CREATE TABLE USUARIOS(
id_usuario INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
nombre_usuario VARCHAR(30),
email VARCHAR(50) UNIQUE NOT NULL,
password_usuario VARCHAR(255) NOT NULL, 
rol BOOLEAN NOT NULL
);

CREATE TABLE JUEGOS(
id_juego INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
nombre_juego VARCHAR(100) NOT NULL, 
plataforma VARCHAR(15), 
categoria VARCHAR(100),
precio DECIMAL(10,2) NOT NULL, 
disponibles INT 
);

CREATE TABLE CARRITO(
id_carrito INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
id_usuario_fk INT UNSIGNED,
id_juego_fk INT UNSIGNED,
cantidad INT UNSIGNED,
FOREIGN KEY(id_usuario_fk) REFERENCES USUARIOS(id_usuario),
FOREIGN KEY(id_juego_fk) REFERENCES JUEGOS(id_juego)
);

CREATE TABLE PEDIDOS(
id_pedido INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
id_usuario_fk INT UNSIGNED, 
fecha DATETIME, 
total DECIMAL(10,2),
estado VARCHAR(20),

FOREIGN KEY(id_usuario_fk) REFERENCES USUARIOS(id_usuario)
);

CREATE TABLE HISTORIAL_PEDIDOS(
id_historial INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
id_pedido_fk INT UNSIGNED, 
id_juego_fk INT UNSIGNED,
cantidad INT UNSIGNED, 
precio_unitario DECIMAL(10,2),

FOREIGN KEY(id_pedido_fk) REFERENCES PEDIDOS(id_pedido), 
FOREIGN KEY(id_juego_fk) REFERENCES JUEGOS(id_juego)
);

